name: steam
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

apps:
  steam:
    command: launcher.sh

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  deps:
    source: empty
    plugin: dump
    stage-packages:
      - libstdc++6
      - lib32stdc++6
      - g++-multilib
      #and the steam deps
      - zenity
      - xterm
      - gnome-terminal
      - xz-utils
      - curl
#      - libgl1-mesa-dri:i386
#      - libgl1-mesa-glx:i386
  steam:
    build-packages:
      - xvfb
    after:
      - deps
    source: src
    plugin: make
  launcher:
    after:
      - steam
    source: launcher
    plugin: dump
